### ISSUE TITLE
license

### ISSUE THREAD

**Issue by hannesm** [zoggy/ocaml-lru-cache#1]
hey, nice stuff.  but why LGPLv3 and not a apache2/MIT/BSD license?

**Comment by zoggy** [comment]
Why not ? :-) Is it a problem ?(I'm not aware of all license subtelties)

**Comment by hannesm** [comment]
for me personally, LGPL is a huge overhead (since I don't understand this huge amount of pseudo-legalese text), BSD/MIT I can easily read and understand (since it is so short)... in the end it depends on what/how much you want to protect (or others to reuse your code).  I tend to stay away from G* licenses

**Comment by hannesm** [comment]
(see e.g. https://fosswire.com/post/2007/04/the-differences-between-the-gpl-lgpl-and-the-bsd/)

**Comment by hannesm** [comment]
the actual issue seems to be that if you have LGPL + other licensed source and use static linking, the other licensed code must be lgpl'ed (https://stackoverflow.com/questions/10130143/gpl-lgpl-and-static-linking), thus LGPL + static linking exception should be fine

**Comment by zoggy** [comment]
Thanks for the pointers.  I usually choose the LGPL for libraries, as it combines the "spirit" of free software à la Stallman, with some compromise to make it usable in proprietary software.

If this proves to be a problem, I can change the license in a next release.

**Comment by hannesm** [comment]
as far as I understand, without linking exception you cannot combine this library with non-LGPL'ed code, which is unfortunate since I'd like to use this for TLS session caching...

**Comment by zoggy** [comment]
Ah ok. I changed the license to BSD3. Do I really need to make a new release now or can you wait until I-don't-know-when?

**Comment by hannesm** [comment]
thanks! waiting until `I don't know when` is a bit tedious, depends on when a new release will happen... I'll for sure not dig into it as long as there's no released BSD-licensed version..

**Comment by zoggy** [comment]
This should happen soon as I think about changing interface: moving the witness key to the functor parameter so that it is not required when creating an instance of the cache.

**Comment by zoggy** [comment]
Release 0.2.0 is now available, with BSD3 license. Should be available soon in opam: https://github.com/ocaml/opam-repository/pull/6195 .

**Comment by hannesm** [comment]
great, thanks! :)

**Comment by hannesm** [comment]
while you link to wikipedia for the cache algorithm, wikipedia says `LRU [...] is actually a family of caching algorithms` -- which one in detail do you implement?

**Comment by zoggy** [comment]
No precise algorithm. Here is who it works.

For a cache with n entries, the cache is composed of

- an array of size n containing pairs of (key, reference to integer),
- a map (Map.Make) from key to pairs (value, reference to integer).

The reference to integer is used in the map to know at which position in the array is this key.
At this position in the array, we have the same reference and the key. The key is required to
remove the last entry of the array when the cache is full. The reference is used to update the
position when entries are shifted in the array. This is faster than updating the map using the key when we have to update the position associated to a key.

When the value associated to a key is required, the key is searched in the map.

- If it is found, then we use the position to shift entries "right" in the array, putting the key at the beginning of the array. For each entry moved in the array, we updated the associated position in the map, using the reference shared between the array and the map.

- If it is not found, then we compute it. If the cache is full (cardinal of the map = cache size), then we remove the last entry of the array from the map (using the key stored at the last position of the array). Then we place the value in the tree and the key at the beginning of the array, shifting all entries "right" and updating the position of their keys in the map.

Is it clear ?

**Comment by hannesm** [comment]
yes, thanks for the explanation!

**Comment by samoht** [comment]
>  If the cache is full (cardinal of the map = cache size),

would be useful to have other ways to detect when the cache is full (for instance if the cache is bigger then a given size, typical use-case: an in-memory filesystem cache). Do you think that would be easy to add?

**Comment by zoggy** [comment]
Note: Computing the cardinal of the map may not be cheap, so I could add an integer in the cache to keep track of the number of entries.

The "size" of the cache in the current implementation is the number of entries in the array.

In your question, is "size" the memory occupied by a value ? In this case, assuming we have a way to know how much memory an OCaml value occupies, the cache could keep track of this size. Then there could be two conditions to remove entries:

- all entries are occupied, we remove the last one,
- (the size of the new value) + (the size of the cached values) - (the size of the last one in the array) is bigger than the max size, then we could remove enough of the least recently used entries so that the cached values size is smaller than the max size.

This could be implemented quite easily, but in another module so that simple "entry-only based" caches would not be impacted by the additional information that should be added.
